### ISSUE TITLE
Issue with Argo + Carthage

### ISSUE THREAD

**Issue by czeluff** [thoughtbot/Argo#80]
I am unable to use Argo successfully in a new app using Carthage as my dependency manager.

https://github.com/czeluff/TryArgo

I have taken the standard Xcode new project and incorporated Argo by linking against Runes & Argo. In User.swift, I attempt to write the 'create' method for a User. I receive the error saying that it cannot find the '<*>' operator. If I attempt to 'import Runes' as well to the top of my file, Xcode builds infinitely.

Apologies if this is user error on my part. Based on the solution, I am happy to recommend new instructions for Argo + Carthage installation that make more sense.

**Comment by gfontenot** [comment]
You definitely need to add `import Runes` to `User.swift`. You probably also have to pin Argo to the `0.3.x` series of releases in order to build with Xcode 6.1/Xcode 6.2. Argo 0.4.x is intended to be used with Swift 1.2 and Xcode 6.3.

**Comment by czeluff** [comment]
Looks as though my Runes.framework was built using Xcode 6.1's xcodebuild, not Xcode 6.3's, resulting in this weird issue with putting 'import Runes' at the top of my file.

**Comment by gfontenot** [comment]
Cool, glad to hear you got it worked out. Once Xcode 6.3 and Swift 1.2 are released, this will all be much less confusing.

**Comment by mgrebenets** [comment]
Sorry to hop on closed issue, but I have very similar one, if not the same.

I'm building OS X (10.10) frameworks with CocoaPods Rome. All builds OK and I have Argo and Runes frameworks ready. Then I try to use them from a Swift script file and get this error when importing both

```
<unknown>:0: error: could not load framework 'Argo'
<unknown>:0: error: could not load framework 'Argo'
<unknown>:0: error: could not load framework 'Argo'
```

Exactly 3 times.

If I don't import Runes, then I get errors like, which is expected.

```
./test.swift:23:4: error: operator is not a known binary operator
                        <^> json <| ["headers", "Accept"]
                        ^
```

I'm using Xcode 6.4 which comes with swift 1.2 and using just `pod 'Argo'` without specifying any branch there.

**Comment by gfontenot** [comment]
I have no idea how Rome works/expects you to work, so I'm not sure how much help I'll be. But my assumption is that because you're trying to use them in a script, you need to modify the framework search paths somehow. Using frameworks in a script isn't super straightforward.
